// PIX Payment Service
// Generates BR Code (QR code payload) and tracks payment status

export interface PixPayment {
  id: string;
  userId: string;
  amount: number;
  brCode: string;
  qrCodeUrl: string;
  status: 'pending' | 'completed' | 'expired';
  createdAt: Date;
  confirmedAt?: Date;
}

import storage from './storage';

const payments = new Map<string, PixPayment>();
const PAYMENTS_KEY = 'payments';

async function persistPayments() {
  const arr = Array.from(payments.values()).map(p => ({
    ...p,
    createdAt: p.createdAt.toISOString(),
    confirmedAt: p.confirmedAt ? p.confirmedAt.toISOString() : null,
  }));
  await storage.writeJSON(PAYMENTS_KEY, arr);
}

async function loadPayments() {
  const arr = await storage.readJSON<any[]>(PAYMENTS_KEY, []);
  for (const raw of arr) {
    payments.set(raw.id, {
      ...raw,
      createdAt: raw.createdAt ? new Date(raw.createdAt) : new Date(),
      confirmedAt: raw.confirmedAt ? new Date(raw.confirmedAt) : undefined,
    });
  }
}

loadPayments().catch((e) => console.error('[pixService] failed to load payments', e));

const PIX_KEY = 'ae927522-3cf8-44b1-9e65-1797ca2ce670';
const PIX_NAME = 'Matheus Alves Cordeiro';
const PIX_CITY = 'BRAZIL';
const PIX_AMOUNT = 590; // R$ 5,90 in cents

/**
 * Generate BR Code (PIX payload) for the given amount
 * This generates a valid EMV QR Code for PIX payments
 */
export function generateBrCode(amountInCents: number = PIX_AMOUNT): string {
  // EMV format for PIX BR Code
  const amount = (amountInCents / 100).toFixed(2);
  
  // Build EMV payload
  const pixKey = PIX_KEY;
  const merchantName = PIX_NAME.toUpperCase().substring(0, 25);
  const city = PIX_CITY.toUpperCase().substring(0, 15);
  const txid = `POKERWIZARD${Date.now()}`.substring(0, 25);
  
  // Payload Format Indicator
  const pfi = '000201';
  
  // Merchant Account Information
  const gui = '0014br.gov.bcb.pix';
  const key = `01${String(pixKey.length).padStart(2, '0')}${pixKey}`;
  const merchantAccount = `26${String(gui.length + key.length).padStart(2, '0')}${gui}${key}`;
  
  // Merchant Category Code
  const mcc = '52040000';
  
  // Transaction Currency (BRL = 986)
  const currency = '5303986';
  
  // Transaction Amount
  const amountField = `54${String(amount.length).padStart(2, '0')}${amount}`;
  
  // Country Code
  const countryCode = '5802BR';
  
  // Merchant Name
  const nameField = `59${String(merchantName.length).padStart(2, '0')}${merchantName}`;
  
  // Merchant City
  const cityField = `60${String(city.length).padStart(2, '0')}${city}`;
  
  // Additional Data Field (txid)
  const txidField = `05${String(txid.length).padStart(2, '0')}${txid}`;
  const additionalData = `62${String(txidField.length).padStart(2, '0')}${txidField}`;
  
  // Build full payload without CRC
  const payloadWithoutCrc = pfi + merchantAccount + mcc + currency + amountField + countryCode + nameField + cityField + additionalData + '6304';
  
  // Calculate CRC16-CCITT
  const crc = calculateCRC16(payloadWithoutCrc);
  
  return payloadWithoutCrc + crc;
}

/**
 * Calculate CRC16-CCITT for BR Code
 */
function calculateCRC16(payload: string): string {
  let crc = 0xFFFF;
  
  for (let i = 0; i < payload.length; i++) {
    crc ^= payload.charCodeAt(i) << 8;
    
    for (let j = 0; j < 8; j++) {
      if ((crc & 0x8000) !== 0) {
        crc = (crc << 1) ^ 0x1021;
      } else {
        crc = crc << 1;
      }
    }
  }
  
  crc = crc & 0xFFFF;
  return crc.toString(16).toUpperCase().padStart(4, '0');
}

/**
 * Create a new payment request (generates QR Code)
 */
export async function createPixPayment(userId: string, amountInCents: number = PIX_AMOUNT) {
  const id = `pix-${Date.now()}`;
  const brCode = generateBrCode(amountInCents);
  
  const payment: PixPayment = {
    id,
    userId,
    amount: amountInCents,
    brCode,
    qrCodeUrl: `data:image/svg+xml;base64,...`, // Would be generated by a QR code library
    status: 'pending',
    createdAt: new Date(),
  };

  payments.set(id, payment);
  await persistPayments();

  return {
    id,
    amount: amountInCents / 100, // Convert back to reais
    brCode,
    // QR code generation would be done on frontend with qrcode.js library
    expiresIn: 1800, // 30 minutes
  };
}

/**
 * Confirm payment (manual verification)
 */
export async function confirmPixPayment(paymentId: string): Promise<PixPayment | null> {
  const payment = payments.get(paymentId);
  if (!payment) return null;

  if (payment.status === 'completed') {
    throw new Error('Payment already completed');
  }

  payment.status = 'completed';
  payment.confirmedAt = new Date();
  await persistPayments();
  return payment;
}

/**
 * Get payment status
 */
export async function getPaymentStatus(paymentId: string): Promise<PixPayment | null> {
  return payments.get(paymentId) || null;
}

// Export all payments for debugging
export function getAllPayments() {
  return Array.from(payments.values());
}

/**
 * Automatically confirm pending payments older than `thresholdMs`.
 * For this prototype, confirming a payment will also activate premium
 * for the associated user by calling `setPremium` from `userService`.
 */
import { setPremium } from './userService';

let _autoConfirmInterval: NodeJS.Timeout | null = null;

export function startAutoConfirmation(intervalMs: number = 15_000, thresholdMs: number = 60_000) {
  if (_autoConfirmInterval) return;
  _autoConfirmInterval = setInterval(async () => {
    try {
      const now = Date.now();
      for (const p of payments.values()) {
        if (p.status === 'pending') {
          const age = now - p.createdAt.getTime();
          if (age >= thresholdMs) {
            p.status = 'completed';
            p.confirmedAt = new Date();
            try {
              await setPremium(p.userId, 30);
              // eslint-disable-next-line no-console
              console.log(`[pixService] Auto-confirmed payment ${p.id} and activated premium for user ${p.userId}`);
            } catch (err) {
              // eslint-disable-next-line no-console
              console.error('[pixService] Failed to set premium for user', p.userId, err);
            }
              // persist each change
              await persistPayments();
          }
        }
      }
    } catch (err) {
      // eslint-disable-next-line no-console
      console.error('[pixService] Auto-confirmation loop error', err);
    }
  }, intervalMs);
}

export function stopAutoConfirmation() {
  if (_autoConfirmInterval) {
    clearInterval(_autoConfirmInterval);
    _autoConfirmInterval = null;
  }
}
